---
title: "Bagging and RFs"
author: "YOUR NAME HERE"
output: html_document
---


```{r setup, include=FALSE}

library(tidyverse)
library(tidymodels)
library(flair)
library(kknn)
library(glmnet)
library(here)
library(rpart.plot)
library(discrim)
library(baguette)

set.seed(98249)
```


```{r, echo = FALSE, message = FALSE, warning = FALSE}

cann <- read_csv("https://www.dropbox.com/s/s2a1uoiegitupjc/cannabis_full.csv?dl=1")


cann <- cann %>%
  mutate(
    Type = factor(Type)
  ) %>%
  rename(
    Spicy = `Spicy/Herbal`
  ) %>%
  drop_na()

cann_cvs <- vfold_cv(cann, v = 5)

cann_recipe <- recipe(Type ~ ., 
                     data = cann) %>%
  step_rm(Strain, Effects, Flavor, Dry, Mouth)

tree_mod <- decision_tree() %>%
  set_engine("rpart") %>%
  set_mode("classification")


tree_wflow <- workflow() %>%
  add_recipe(cann_recipe) %>%
  add_model(tree_mod)



tree_fit_1 <- tree_wflow %>%
  fit(cann)


tree_fitted <- tree_fit_1 %>% 
  pull_workflow_fit()

rpart.plot(tree_fitted$fit)
```


```{r}
cann %>%
  bind_cols(
    predict(tree_fitted, cann, type = "prob")
  ) %>%
  gain_capture(truth = Type,
               .pred_hybrid, .pred_indica, .pred_sativa)
```

```{r}
set.seed(9374534)
splits <- cann %>% 
  initial_split(0.5, strata = Type)

cann_1 <- splits %>% training()
cann_2 <- splits %>% testing()

dim(cann_1)
dim(cann_2)
```

```{r}
tree_1 <- tree_wflow %>%
  fit(cann_1)

tree_2 <- tree_wflow %>%
  fit(cann_2)
```


```{r}
tree_1 %>% 
  pull_workflow_fit() %$%
  fit %>%
  rpart.plot()
```


```{r}
tree_2 %>% 
  pull_workflow_fit() %$%
  fit %>%
  rpart.plot()
```

## Bagging

```{r baguette}
library(baguette)

bag_tree_spec <- bag_tree() %>%
  set_engine("rpart", times = 5) %>%
  set_mode("classification")

```


```{r}
bag_tree_wflow <- workflow() %>%
  add_recipe(cann_recipe) %>%
  add_model(bag_tree_spec)

bag_tree_fit <- bag_tree_wflow %>%
  fit(cann)

## (this code may take a while!)
```


```{r}
bag_tree_fit %>% pull_workflow_fit()
```

## Random Forests

Randomly choose a few of the predictors to include in the data:

```{r}
cann_reduced <- cann %>%
  select(1,2, sample(5:65, 30))

cann_reduced
```

```{r, echo = FALSE}
cann_recipe_2 <- recipe(Type ~ ., 
                     data = cann_reduced) %>%
  step_rm(Strain)

tree_fit_reduced <- workflow() %>%
  add_recipe(cann_recipe_2) %>%
  add_model(tree_mod) %>%
  fit(cann_reduced)

rpart.plot(tree_fit_reduced %>% pull_workflow_fit() %$% fit)
```




# Your turn

## Find the best *bagged* model for the cannabis data
## Find the best *random forest* model for the cannabis data
## Report some metrics on your models
